### ISSUE TITLE
Colore etichetta tab

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/bt-dash#1]
Se il valore PNL <0 l'etichichetta del tab è rossa

**Comment by aberbenni** [comment]
Vedi https://github.com/xamul-it/bt-dash/issues/2#issuecomment-1067782163

**Comment by xamul-it** [comment]
{
    "21145807251": {
        "param_selcperc": 4,
        "param_rperiod": 1,
        "param_vperiod": 100,
        "param_mperiod": 80,
        "param_fperiod": 45,
        "param_reserve": 0.1,
        "fromdate": "01/01/2010",
        "todate": "31/12/2012",
        "ptf inizio": 50000.0,
        "PNL": 0.3116638177721802,
        "trades": 253,
        "SQN": 1.0683310169287525,
        "Sharpe": 1.152484147308569,
        "VWR": 4.576021580958125
    }
}
