### ISSUE TITLE
Colore importi

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/bt-dash#2]
Gli importi negativi sono rappresentati con testo rosso

**Comment by aberbenni** [comment]
Mi farebbe comodo che i valori in output `PNL , trades, SQN, Sharpe, VWR` fossero passati come numeri invece che come stringhe (proprio come i `param_*`).

```
{
  "param_selcperc": 4,
  "param_rperiod": 1,
  "param_vperiod": 100,
  "param_mperiod": 100,
  "param_fperiod": 40,
  "param_reserve": 0.1,
  "param_sl": 0.1,
  "fromdate": "01/05/2010",
  "todate": "01/12/2020",
  "ptf inizio": "60000",
  "PNL": "8.30000",
  "trades": "633",
  "SQN": "2.191",
  "Sharpe": "0.781",
  "VWR": "7.903"
}
```

**Comment by xamul-it** [comment]
Fatto tranne le date
{
    "21145807251": {
        "param_selcperc": 4,
        "param_rperiod": 1,
        "param_vperiod": 100,
        "param_mperiod": 80,
        "param_fperiod": 45,
        "param_reserve": 0.1,
        "fromdate": "01/01/2010",
        "todate": "31/12/2012",
        "ptf inizio": 50000.0,
        "PNL": 0.3116638177721802,
        "trades": 253,
        "SQN": 1.0683310169287525,
        "Sharpe": 1.152484147308569,
        "VWR": 4.576021580958125
    }
}

**Comment by aberbenni** [comment]
`ptf inizio` e `trades` possono avere decimali?
