### ISSUE TITLE
Url Errato

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/bt-dash#4]
La cartella out è configurata con un percorso relativo
../out
L'appticativo genere un url errato nei backup:
http://213.171.162.127/backup/20220309../out/CandleX-180/results.json

**Comment by aberbenni** [comment]
Mi puoi postare la configurazione che stai usando? File `constants.js`?

**Comment by xamul-it** [comment]
Ecco le configurazioni:
const constants = {
  API_BASE_URL: 'http://213.171.162.127/dash',
  API_BASE_FOLDER: '../out',
  API_BACKUP_FOLDER: '../backup',
  API_INDEX_FILE: '/index.json',
  API_TICKER_DATA_FILE: '/results.json',
  STATS_FILE: '/stats.html',

  //Locale
  APP_LOCALE: 'it-IT',

}
