### ISSUE TITLE
ReferenceError: Can't find variable: save

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/bt-dash#6]
Caricando il file stats.html si vrifica l'errore `ReferenceError: Can't find variable: save` per la presenza nel codice HTML di questo evento `<body onload="save()">` senza che esista la corrispondente funzione Javascript. 
Se possibile elimina la chiamata `onload`.

**Comment by aberbenni** [comment]
Su Chrome l'errore viene indicato come:
```
Uncaught ReferenceError: save is not defined
    at onload (stats.html:18:23)
```

**Comment by xamul-it** [comment]
Non si verifica +
